### ISSUE TITLE
LIRC import misbehaviour for Pioneer Code

### ISSUE THREAD

**Issue by mxbr** [bengtmartensson/harctoolboxbundle#91]
Hi, me again :)
See this example Pronto Code:
```
0000 0068 0000 0044 0168 00B4 0016 0043 0016 0043 0016 0016 0016 0016 0016 0016 0016 0043 0016 0016 0016 0043 0016 0016 0016 0016 0016 0043 0016 0043 0016 0043 0016 0016 0016 0043 0016 0016 0016 0043 0016 0016 0016 0016 0016 0043 0016 0043 0016 0016 0016 0016 0016 0043 0016 0016 0016 0043 0016 0043 0016 0016 0016 0016 0016 0043 0016 0043 0016 0016 0016 06D9 0168 00B4 0016 0043 0016 0043 0016 0043 0016 0043 0016 0016 0016 0043 0016 0016 0016 0043 0016 0016 0016 0016 0016 0016 0016 0016 0016 0043 0016 0016 0016 0043 0016 0016 0016 0043 0016 0016 0016 0016 0016 0016 0016 0043 0016 0043 0016 0016 0016 0043 0016 0016 0016 0043 0016 0043 0016 0043 0016 0016 0016 0016 0016 0043 0016 0016 0016 06D9
```
It is parsed as: protocol = Pioneer, device = 163, obc = 153 (+ one other decode)

Now lets assume we have a LIRC file captured which has the same code (CONDITIONMEMORY)

```

# Please make this file available to others
# by sending it to <winlirc.configs@gmail.com>
#
# this config file was automatically generated
# using lirc-0.9.0(SerialDevice) on Fri Jan 01 17:23:24 2016
#
# contributed by 
#
# brand:                       Pioneer
# model no. of remote control: VXX2700
# devices being controlled by this remote:DV-533K
#

begin remote

  name  VXX2700
  bits           32
  flags SPACE_ENC|CONST_LENGTH
  eps            30
  aeps          100

  header       8624  4194
  one           577  1554
  zero          577   489
  ptrail        588
  gap          90016
  toggle_bit_mask 0x0

      begin codes
          POWER                    0xC53A9966 0xF50A3DC2
          LASTMEMORY               0xC53A9966 0xF50A6F90
          CONDITIONMEMORY          0xC53A9966 0xF50A8D72
          OPEN/CLOSE               0xC53A9966 0xF50A6D92
      end codes

end remote

```

The codes are imported into the scrutinizer as:

protocol = NEC2, device = 163, obc = 153 (+ one other decode), 

However if you import them into the remote view (parametric remote) and then export it to a new LIRC file (or whatever format), only the first decode is recognized following into wrong codes

http://abload.de/img/untitled55ujv.png

Im not sure if this isnt a lirc problem , but in any case there is something wrong at some point

**Comment by bengtmartensson** [comment]
This is a known problem. The problem is that (some) Pioneer remotes send "two commands" for each key press, and DecodeIr recognizes this as two different commands. (Turn on Options -> Print decodes to console" to see both, not just the "censored" version). See the doc for the "Pioneer" protocol, second para. DecodeIR is a third-party component, and a fix is not likely. On a long-time scale, I plan to replace it, see https://github.com/bengtmartensson/IrpTransmogrifier 

There is the "Pioneer-Mix" protocol (written by myself), so with a considerable amount of manual work, you can cook up a remote using that protocol, and that can be exported ot Lirc, however, only in raw form.

Also note that Pioneer and NEC2 only differs in the frequency, which Lirc does not measure (but "guesses" 38k _all of the time_...
